/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthDashboardImport } from './routes/_auth.dashboard'
import { Route as AuthFrontOfficeReservationsIndexImport } from './routes/_auth.front-office/reservations/index'
import { Route as AuthFrontOfficeReservationsReservationIdImport } from './routes/_auth.front-office/reservations/$reservationId'

// Create Virtual Routes

const ProductsLazyImport = createFileRoute('/products')()
const OrdersLazyImport = createFileRoute('/orders')()
const CustomersLazyImport = createFileRoute('/customers')()
const AnalyticsLazyImport = createFileRoute('/analytics')()
const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const ProductsLazyRoute = ProductsLazyImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))

const OrdersLazyRoute = OrdersLazyImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/orders.lazy').then((d) => d.Route))

const CustomersLazyRoute = CustomersLazyImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/customers.lazy').then((d) => d.Route))

const AnalyticsLazyRoute = AnalyticsLazyImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/analytics.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFrontOfficeReservationsIndexRoute =
  AuthFrontOfficeReservationsIndexImport.update({
    id: '/front-office/reservations/',
    path: '/front-office/reservations/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthFrontOfficeReservationsReservationIdRoute =
  AuthFrontOfficeReservationsReservationIdImport.update({
    id: '/front-office/reservations/$reservationId',
    path: '/front-office/reservations/$reservationId',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsLazyImport
      parentRoute: typeof rootRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersLazyImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersLazyImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    '/_auth/front-office/reservations/$reservationId': {
      id: '/_auth/front-office/reservations/$reservationId'
      path: '/front-office/reservations/$reservationId'
      fullPath: '/front-office/reservations/$reservationId'
      preLoaderRoute: typeof AuthFrontOfficeReservationsReservationIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/front-office/reservations/': {
      id: '/_auth/front-office/reservations/'
      path: '/front-office/reservations'
      fullPath: '/front-office/reservations'
      preLoaderRoute: typeof AuthFrontOfficeReservationsIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthFrontOfficeReservationsReservationIdRoute: typeof AuthFrontOfficeReservationsReservationIdRoute
  AuthFrontOfficeReservationsIndexRoute: typeof AuthFrontOfficeReservationsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthFrontOfficeReservationsReservationIdRoute:
    AuthFrontOfficeReservationsReservationIdRoute,
  AuthFrontOfficeReservationsIndexRoute: AuthFrontOfficeReservationsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/about': typeof AboutLazyRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/customers': typeof CustomersLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/products': typeof ProductsLazyRoute
  '/dashboard': typeof AuthDashboardRoute
  '/front-office/reservations/$reservationId': typeof AuthFrontOfficeReservationsReservationIdRoute
  '/front-office/reservations': typeof AuthFrontOfficeReservationsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/about': typeof AboutLazyRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/customers': typeof CustomersLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/products': typeof ProductsLazyRoute
  '/dashboard': typeof AuthDashboardRoute
  '/front-office/reservations/$reservationId': typeof AuthFrontOfficeReservationsReservationIdRoute
  '/front-office/reservations': typeof AuthFrontOfficeReservationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/about': typeof AboutLazyRoute
  '/analytics': typeof AnalyticsLazyRoute
  '/customers': typeof CustomersLazyRoute
  '/orders': typeof OrdersLazyRoute
  '/products': typeof ProductsLazyRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/front-office/reservations/$reservationId': typeof AuthFrontOfficeReservationsReservationIdRoute
  '/_auth/front-office/reservations/': typeof AuthFrontOfficeReservationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/profile'
    | '/about'
    | '/analytics'
    | '/customers'
    | '/orders'
    | '/products'
    | '/dashboard'
    | '/front-office/reservations/$reservationId'
    | '/front-office/reservations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/profile'
    | '/about'
    | '/analytics'
    | '/customers'
    | '/orders'
    | '/products'
    | '/dashboard'
    | '/front-office/reservations/$reservationId'
    | '/front-office/reservations'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/profile'
    | '/about'
    | '/analytics'
    | '/customers'
    | '/orders'
    | '/products'
    | '/_auth/dashboard'
    | '/_auth/front-office/reservations/$reservationId'
    | '/_auth/front-office/reservations/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AnalyticsLazyRoute: typeof AnalyticsLazyRoute
  CustomersLazyRoute: typeof CustomersLazyRoute
  OrdersLazyRoute: typeof OrdersLazyRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AboutLazyRoute: AboutLazyRoute,
  AnalyticsLazyRoute: AnalyticsLazyRoute,
  CustomersLazyRoute: CustomersLazyRoute,
  OrdersLazyRoute: OrdersLazyRoute,
  ProductsLazyRoute: ProductsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/profile",
        "/about",
        "/analytics",
        "/customers",
        "/orders",
        "/products"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard",
        "/_auth/front-office/reservations/$reservationId",
        "/_auth/front-office/reservations/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/analytics": {
      "filePath": "analytics.lazy.tsx"
    },
    "/customers": {
      "filePath": "customers.lazy.tsx"
    },
    "/orders": {
      "filePath": "orders.lazy.tsx"
    },
    "/products": {
      "filePath": "products.lazy.tsx"
    },
    "/_auth/dashboard": {
      "filePath": "_auth.dashboard.tsx",
      "parent": "/_auth"
    },
    "/_auth/front-office/reservations/$reservationId": {
      "filePath": "_auth.front-office/reservations/$reservationId.tsx",
      "parent": "/_auth"
    },
    "/_auth/front-office/reservations/": {
      "filePath": "_auth.front-office/reservations/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
